#!/bin/bash


date > ~/date.log

_placeHere=$(pwd)

source build/envsetup.sh

target="shieldtablet"
LINEAGE_DEVICES_ONLY="true"
LUNCH_MENU_CHOICES=(full-eng)

source vendor/lineage/vendorsetup.sh

lunch lineage_${target}-userdebug

cd ${_placeHere}

${_placeHere}/build/soong/soong_ui.bash --make-mode -j bacon

date >> ~/date.log
