#!/bin/bash


date > ~/date.log

source build/envsetup.sh

target="shieldtablet"
LINEAGE_DEVICES_ONLY="true"
LUNCH_MENU_CHOICES=(full-eng)

source vendor/lineage/vendorsetup.sh

lunch lineage_${target}-userdebug

croot

brunch shieldtablet

date >> ~/date.log